service: image-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    BUCKET_NAME: rsgstorage
    # RGS_ACCESS_KEY_ID: ${env:RGS_ACCESS_KEY_ID} 
    # RGS_SECRET_ACCESS_KEY: ${env:RGS_SECRET_ACCESS_KEY}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
          Resource: arn:aws:s3:::rsgstorage/*

functions:
  imageHandler:
    handler: handler.imageHandler
    timeout: 30 
    events:
      - http:
          path: image/{proxy+}
          method: get
          request:
            parameters:
              querystrings:
                width: false
                height: false
                format: false
                quality: false
          cors: true

plugins:
  - serverless-offline
